[project]
name = 
version = "0.0.0"

[tool.setuptools.packages.find]
where = ["src/"]
include = 

[tool.pytest.ini_options]
addopts = ["-ra", "--strict-markers", "--strict-config",]
xfail_strict = true
filterwarnings = ["error"]
log_cli_level = "info"
testpaths = ["tests"]